name: CI Notifications Post-to-Slack function Invoker
description: function invoker
inputs:
    status:
        description: Status of PR Check(success / failure)
        required: true
    failure_step:
        description: Step Name of Failure caused(need if status is failure)
        required: false
    begintime:
        description: Beginning time of checks execution
        required: true
    head_sha:
        description: Merge HEAD branch SHA
        required: false
    base_sha:
        description: Merge BASE branch SHA
        required: false
    pr_number:
        description: PullRequest Number
        requried: false
    pr_title:
        description: PullRequest Title
        required: false
    mode:
        description: Report Mode(diff or branch)
        required: true
    report_name:
        description: Name of Reporter
        required: true
    support_info:
        description: Support Info Markdown(applied to details attachment)
        required: false
runs:
    using: node12
    main: index.js
