name: CI Notifications Post-to-Slack function Invoker
description: function invoker
inputs:
    status:
        description: Status of PR Check(success / failure)
        required: true
    failure_step:
        description: Step Name of Failure caused(need if status is failure)
        required: false
    begintime:
        description: Beginning time of checks execution
        required: true
    head_sha:
        description: Merge HEAD branch SHA
        required: true
    base_sha:
        description: Merge BASE branch SHA
        required: true
    pr_number:
        description: PullRequest Number
        requried: true
    pr_title:
        description: PullRequest Title
        required: true
runs:
    using: node12
    main: index.js
